  <h2> Usage </h2>
  <pre class="prettyprint">

        new Ajax.Request('api/<action>', {
            method: 'get',
            parameters: params,
            onSuccess: function(response) {
                console.log(response.responseJSON);
            };
        }); 
  </pre> 

<!--
    <h4> api/index </h4>
    <i> params </i>
  <pre class="prettyprint">
    {
    }</pre>
  <button type="submit" onclick="demo('index')">Go</button>
  <pre class="prettyprint" id='index'></pre>

    <h4> Install </h4>
    <i> params </i>
  <pre class="prettyprint">

    {
        action: install 
    }
  </pre>
  <button type="submit" onclick="demo('install', { action: 'install' })">Go</button>
  <pre class="prettyprint" id='install'></pre>


    <h4> Installed </h4>
    <i> params </i>
  <pre class="prettyprint">

    {
        action: installed
    }
  </pre>
  <button type="submit" onclick="demo('installed', { action: 'installed' })">Go</button>
  <pre class="prettyprint" id='installed'></pre>
-->

    <h4> question/api/random </h4>
    <i> params </i>
  <pre class="prettyprint">
    {
    }</pre>
  <button type="submit" onclick="demo('question/api/random')">Go</button>
  <pre class="prettyprint" id='question/api/random'></pre>

  <script>
    function demo(action, params) {

        new Ajax.Request(action, {
            method: 'get',
            parameters: params,
            onSuccess: function(response) {
               console.log(response.responseJSON);
               $(action).update(jsl.format.formatJson(
                    Object.toJSON(response.responseJSON)
               )); 
            },
            onFailure: function(response) {
               $(demoContainerId).insert(Object.toJSON(
                    {
                        success: false,
                        msg: "Api unavailable (connection/ajax failure)"
                    }        
               )); 
            }
        });
    }
  </script>
