
<h1>Welcom in Magento Quiz API</h1>
<div>
<br />
<br />
<br />
<p> Stuff: </p>
<a href="http://www.magestudyguide.com/">Mage Study Guide</a><br />
<a href="http://magentools.com/blog/magento-certification-preparation-study-guide-answers/">Magento Certification Preparation</a><br />
<a href="http://www.magentocommerce.com/certification/">About Certification</a><br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
</div>
