CREATE TABLE question_reference (
  id INT(10) AUTO_INCREMENT,
  question_id int(10) NOT NULL, 
  url TEXT NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_QUESTION_REFERENCE_QUESTION FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
