CREATE TABLE question (
  id INT(10) PRIMARY KEY AUTO_INCREMENT,
  question TEXT NOT NULL ,
  category_id int(10) DEFAULT NULL,
  user_email VARCHAR(255) DEFAULT NULL, 
  CONSTRAINT FK_QUESTION_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT FK_QUESTION_USER FOREIGN KEY (user_email) REFERENCES user (email) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
