CREATE TABLE answer (
  id INT(10) AUTO_INCREMENT,
  question_id int(10) NOT NULL, 
  value TEXT NOT NULL,
  valid TINYINT(1),
  PRIMARY KEY (id),
  CONSTRAINT FK_ANSWER_QUESTION FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=274063 DEFAULT CHARSET=utf8 
