<div class="page-header">
    <h1>Add question</h1>
</div>
<form action="/question/add/post" method="post" role="form">

    <input name="question" type="text" placeholder="Question" class="form-control">
    <br />

    <div class="input-group">
      <input name="answers[0][value]" type="text" placeholder="Answer" class="form-control">
      <span class="input-group-addon">
        <span> valid </span>
        <input name="answers[0][is_valid]" type="checkbox">
      </span>
    </div>
    <br />

    <div class="input-group">
      <input name="answers[1][value]" type="text" placeholder="Answer" class="form-control">
      <span class="input-group-addon">
        <span> valid </span>
        <input name="answers[1][is_valid]" type="checkbox">
      </span>
    </div>
    <br />

    <div class="input-group">
      <input name="answers[2][value]" type="text" placeholder="Answer" class="form-control">
      <span class="input-group-addon">
        <span> valid </span>
        <input name="answers[2][is_valid]" type="checkbox">
      </span>
    </div>
    <br />

    <div class="input-group">
      <input name="answers[3][value]" type="text" placeholder="Answer" class="form-control">
      <span class="input-group-addon">
        <span> valid </span>
        <input name="answers[3][is_valid]" type="checkbox">
      </span>
    </div>
    <br />

    <button type="submit" class="btn">Submit</button>
</form>
