<div class="page-header">
    <h1>List of questions</h1>
</div>

<?php if (count($questions)): ?>
  <ul class="list-group">
    <?php foreach($questions as $question): ?>
        <div class="input-group">
          <li class="list-group-item input-group">
          <div><?php echo $question['question']; ?></div>
          <small class="text-muted">onwer: <?php echo $question['user_email']; ?></small>
          </li>
          <?php if ($question['can_edit']): ?>
              <a class="glyphicon glyphicon-edit input-group-addon btn btn-info" href="#"> </a>
          <?php else: ?>
              <span class="glyphicon glyphicon-thumbs-up input-group-addon"> </span>
          <?php endif; ?>
        </div>
    <?php endforeach; ?>
  </ul>
<?php else: ?>
    <h3>No questions? Add <a href="/question/add"><span class="label label-default">new</span></a>!</h3> 
<?php endif; ?>

