CREATE TABLE session (
  id INT(10) AUTO_INCREMENT,
  session BINARY(32) NOT NULL UNIQUE,
  user_email VARCHAR(255),
  PRIMARY KEY (id),
  CONSTRAINT FK_SESSION_USER FOREIGN KEY (user_email) REFERENCES user (email) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
